### PR TITLE
Temporarily change euid and egid when searching for processes with sp…

### PR DESCRIPTION
**Pull request by iDarkTemplar**
…ecific pid.

This should fix https://github.com/OpenRC/openrc/issues/180

https://github.com/gentoo/gentoo/pull/6176 is also needed to fix issue with git-daemon

### CODE REVIEW

**Comment by williamh** [comment]
Can you please check the patch I posted on the original issue? If you are just running into a permission issue when checking the name spaces, I would rather just skip checking the name spaces than change uid/gid to avoid the permission issue.

**Comment by iDarkTemplar** [comment]
I already did and responded in original issue: https://github.com/OpenRC/openrc/issues/180#issuecomment-343987970

**Comment by williamh** [comment]
I will keep this open for a release or so to monitor for more issues, but I don't think we need to do this since the issue that it addresses is actually in librc itself.

**Comment by williamh** [comment]
The searching is done in rc_find_pids, so it would probably be better to do anything like this there than in either of the supervisors.

**Comment by iDarkTemplar** [comment]
Closing this request since issue is fixed in 0.34.7.

**Pull request closed without merging**
