### PR TITLE
tmpfiles: Accept filenames as command line arguments

### PR DESCRIPTION
**Pull request by floppym**
This brings us closer to the behavior of systemd-tmpfiles.

My end goal is to be able to call this via an eclass function in pkg_postinst in ebuilds.

### CODE REVIEW

**Comment by dwfreed** [comment]
LGTM

**Comment by floppym** [comment]
I pushed a small fix to the first commit.

**Comment by robbat2** [comment]
Conditionally I accept it; there's one change needed:
You must be able to handle arguments that have whitespace in the filename.

**Comment by floppym** [comment]
Heh, show me a reasonable way to do that with portable sh syntax and I'll get right on that.

**Comment by robbat2** [comment]
Doing that with portable sh:
Method 1:
Use \0 as a seperator rather than a space, adjusting IFS when you want to read that variable.

Method 2:
Keep them in arguments, rather than shifting them out; then loop over arguments:
```
# Options pass, replaces $# -gt 0
FILEMODE=0
for opt in "$@" ; do
  if [ "${f:0:2}" != "--" ]; 
    FILEMODE=1
    continue
  fi
  # existing case statement, with $opt instead of $1
  # drop the shift
done
# Arguments pass
if [ $FILEMODE -eq 1 ]; then 
  for f in "$@" ; do
    [ "${f:0:2}" == "--" ] && continue
    process "$f"
  done
  exit # ...
fi
```

**Comment by floppym** [comment]
Thanks. I think using `\0` as a separator might break some shells. I can probably make your second method work.

**Comment by floppym** [comment]
In the case of having no files specified on the command line, we need to generate a sorted union of filenames from `/etc/tmpfiles.d/*.conf`, `/run/tmpfiles.d/*.conf` and `/usr/lib/tmpfiles.d/*.conf`. I cannot see any way to accomplish this in POSIX sh while also preserving whitespace.

Your idea of using `\0` as a delimiter simply does not work; both bash and dash eat any `\0` characters that are stored in variables.

tmpfiles.sh is currently broken when filesnames have whitespace, so my patchset does not introduce a regression here. If you want to fix it, please undertake it as a separate issue.

**Comment by dwfreed** [comment]
@williamh any objections to merging this?

**Pull request closed without merging**
