### PR TITLE
scripts/Makefile: respect SBINDIR with MKSYSVINIT

### PR DESCRIPTION
**Pull request by udeved**
Use SBINDIR in the scripts Makefile and fix the symlinks if MKSYSVINIT=yes

### CODE REVIEW

**Comment by williamh** [comment]
The first commit on this p/r looks good, but I have concerns about the second and third ones. The first commit fixes sbindir on the symlinks and that is correct. In the second one, why do you convert the symlinks to absolute symlinks instead of leaving them as relative? The third one breaks the shutdown wrapper by linking it to shutdown instead of openrc-shutdown.

**Comment by udeved** [comment]
Hi @williamh 

I am just experimeting, I perhaps should have done it i a separate patch branch.

Reaso for second commit was, that all the symlinks in the resulting package were broke.
The were a dead end symlink, pointing to a non existing file.
Now what I don't know, if this is connected to using a prefix as opposed to gentoo.
The third commit was donne, because I have had trouble to poweroff the system from plasma. It shutdown, but the message states "reboot" annd the system just keeps powered on. Something is still wrong with the shutdown.

**Comment by udeved** [comment]
Reason to make it absolute path was this...

`ln -sf ..//usr/lib/rc/bin/rc-sstat /build/openrc/pkg/openrc//usr/bin/rc-sstat`

The double slash renders the symlink broke.

**Comment by williamh** [comment]
Correct, you should always keep the master branch clean; all pull requests should be done with branches.

**Comment by udeved** [comment]
Can you close it and I'll reopen a patch PR.

**Pull request closed without merging**
