### PR TITLE
seedrng: incorporate various improvements

### PR DESCRIPTION
**Pull request by zx2c4**
There have been a number of subtle improvements and cleanups to seedrng,
including using openat and locking the directory fd instead of a
separate lock file. Also various stylistic cleanups.

### CODE REVIEW

**Comment by zx2c4** [comment]
CC @williamh @thesamesam

**Review by thesamesam — APPROVED** [review]
Thank you!

**Comment by williamh** [comment]
@thesamesam  As I said on IRC, I'm curious what @zx2c4  reason was for changing the cleanup/atexit setup to gotos.

**Comment by zx2c4** [comment]
While not strictly necessary, I added in a `free(seed_dir)` to the end of main and made the function flow go into that. Of course we could omit the entire cleanup sequence, since the OS does that for us anyway. But since we're already closing those fds, might as well free the seed_dir var too.

**Pull request closed without merging**
