### PR TITLE
add CoC based on the Contributor Covenant project

### PR DESCRIPTION
**Pull request by vapier**

### CODE REVIEW

**Comment by williamh** [comment]
I need to think about a reporting address, but it really isn't openrc@g.o.

**Comment by vapier** [comment]
short of e-mailing one of us directly, openrc@g.o is the only other possible e-mail contact point atm

other options would be to use GH issues or GH discussions.  i'm fine with that wrt transparency, but i can imagine that not everyone would feel comfortable making public reports, and i don't think it's possible to make private reports via these channels.

**Comment by williamh** [comment]
@vapier  My concern about openrc@g.o is that we don't control who that goes to.

 A private email could be an option, but to be honest I would prefer that github has private issues or discussions, and if they do I would do that.
I will open up a support ticket with them about it.

Also, you might want to download the original CoC from
[here](https://www.contributor-covenant.org/version/2/1/code_of_conduct/code_of_conduct.md). The one you put in has references to the "git community".

**Comment by williamh** [comment]
I just opened a ticket asking about this.

**Comment by CITIZENSIXTYNINE** [comment]
I'm not an OpenRC contributor but I think that I can comment on this as this is an open-source project with a community.

Codes of Conduct that prohibit certain groups of people from contributing do **NOT** belong in Open Source projects.

**Comment by vapier** [comment]
you're going to have to be less vague as to your actual concerns.  who, exactly, is being prohibited here.

**Comment by fufik** [comment]
@vapier What really is vague though, that is the proposed version of CoC from Contributor Covenant. Although it is *intended* to be a document that describes clear rules and unacceptable behaviours, it **does not** include a __finite__ list of undesirable actions and thus any act may be treated as a violation of the CoC according to that line:      
_"Other conduct which could reasonably be considered inappropriate in a professional setting"._       
There already have been dramas regarding that version of Code of Conduct.      
If you really want to adopt one, why not a like of the Gentoo's which has clear cut and concise rules: https://wiki.gentoo.org/wiki/Project:Council/Code_of_conduct ?

**Comment by vapier** [comment]
i don't think that comparison is accurate.  the Gentoo CoC linked provides *examples* ... it is by no means an exhaustive list.  Contributor Covenant also provides examples, many of which overlap with Gentoo's own CoC.

i'm not sure if you're trying to claim that Gentoo's CoC has been drama free.  it most certainly has not, and continues to not.

the reason for going with Contributor Covenant over Gentoo:
* we can't just copy & paste Gentoo's CoC.  it clearly has Gentoo-specific escalation/resolution paths that no one wants (e.g. William, myself, and Gentoo).  it doesn't make sense in a project that is independent of Gentoo.
* Contributor Covenant has been adopted by a ton more projects than Gentoo, and projects that are significantly larger.  Gentoo's CoC has been adopted by ... Gentoo.  in a historical context, this makes sense (Gentoo's CoC long predates Contributor Covenant), but it's not 2007 anymore, and the ecosystem has updated.

**Comment by fufik** [comment]
@vapier 
'but it's not 2007 anymore"    
What do you mean by that?

**Comment by fufik** [comment]
@vapier Well, I didn't know, that Gentoo CoC also provided examples of behavior, not clear rules. At least I did not find any mention of that. My bad. Then it's a bad example. 

Your argument though is essentially that:
* You don't want to copy Gentoo's CoC
* CC was adopted by more projects and Gentoo's wasn't and it's not 2007....?    

What? Why should it matter, how "popular" some CoC is?     
Why would you like to adopt one in the first place?

**Comment by vapier** [comment]
it isn't about popularity, it's about consistency, and it's about being lazy.  if Contributor Covenant is good enough for such a large diverse set of projects and developer communities, then it's fine for OpenRC, and it's likely to be seen & understood by people already.  Gentoo CoC isn't going to be known outside of Gentoo.

sorry, but i'm not going to argue "why CoC".  there are plenty of articles out there on the topic already.

**Comment by fufik** [comment]
@vapier
So far I only know about it by cringeworthy cases of witch-hunting that its creator also actively seeks to start. You want to witch-hunt, am I correct?

**Comment by vapier** [comment]
it sounds like you're operating in bad faith and making unfounded assumptions about other people.  i suggest you take a moment to rethink.

**Comment by fufik** [comment]
@vapier No, I am returning you the favour of a bad argument. There are plenty articles online on anything out there, both in favour and against something — anyone can write such an article. But that was not my question. My question was, what specific goal **you** have in mind and what **you** consider important when adopting the CoC, what problems **you** are trying to solve and whether you consider all possible outcomes and consequences. I, for instance, don't want the software I enjoy using, to be ridden in threads like [this](https://github.com/opal/opal/issues/941) 
Do you consider a possibility of that situation a "lesser evil"?

**Comment by vapier** [comment]
if the reason you're asking about specifics is because you're trying to sus out who we're trying to ban/kick out but not say, there isn't anyone.  this isn't a conspiracy that as soon as this is merged, we're going to spring it on people in an aha! moment.  if we wanted to ban someone, we can already do that without an explicit CoC -- we're admins on the project and can block people & lock threads at entirely our own discretion already.

as i said, the goal is laid out in the Contributor Covenant intro itself.  there's nothing more to it.  either you trust us that we're being honest and that should be enough, or you don't trust us and see conspiracies, at which point this debate is pointless -- nothing i say is going to convince you otherwise.

**Comment by fufik** [comment]
@vapier I never said a thing about conspiracy from your side. Was a little sarcastic — maybe! ;)    
You are correct, indeed you can ban anyone you want even now. My point is just that picking a specific variant of CoC (the aforementioned Contributor Covenant) can signal to and attract certain sorts of people. 
This is also the reason why I suggested picking something other than Contributor Covenant. 
Those people then *could* use the CoC not the way you intend it to be used, for some good old social pressure.     

Well, social contracts mostly NEVER work the way they are intended to. And especially if the creator of the CoC (I wholeheartedly believe) would endorse it. The one who started the thread I linked is actually no one else than the creator of the Contributor Covenant CoC, you can see their name right there, at the bottom of its official website https://www.contributor-covenant.org/      

But well, do whatever you wish. I don't have the authority to command you around. Just my 2p in this global comedy show.     

I'll be happy either way, but I'm just kinda lazy to write my own init system if good alternatives die because they were "fighting meritocracy". Writing tools is fun, though.

**Comment by vapier** [comment]
some fair points.  if the concern is about people attempting to abuse via the CoC, i'm not sure any particular CoC will make that better/worse.  Gentoo's CoC certainly hasn't been a cure-all -- the project has seen plenty of its own mind numbing dumpster fire threads.

it's not like there's an overwhelming number of CoC's to choose from, and i'm certainly not interested in [authoring my own](https://xkcd.com/927/).  i'm not familiar with the person you call out specifically, and i doubt i'll ever cross paths with them.  i look at it from this angle: if Contributor Covenant is working for large projects (e.g. git & the Linux kernel), then that's good enough for me.

**Comment by winterdaemon** [comment]
The [systemd devs have agreed](https://github.com/systemd/systemd/pull/10233) on a [code of conduct](https://github.com/systemd/systemd/blob/main/docs/CODE_OF_CONDUCT.md) based on [The Ruby Community Conduct Guideline](https://www.ruby-lang.org/en/conduct/). Why not use something like that? As [this person said](https://github.com/systemd/systemd/issues/10148#issuecomment-423866291), **it covers all the bases** while being fairly unintrusive. It's simple, apolitical and **to the point**.

**Comment by williamh** [comment]
I agree with @vapier  that if it is good enough for all of [these projects](https://www.contributor-covenant.org/adopters/), it should be fine for us. As he also said, no CoC is going to be a cure-all unfortunately.
The only reason I haven't nerged this yet is I haven't quite decided what to do about the reporting address.
As I said above, openrc@g.o is basically a public address (any Gentoo developer, even folks who have nothing to do with openrc) can be on it. Also, Gentoo is a downstream user, but they do not have any jurisdiction over OpenRC.
The other way to do it would be to have people email us directly, but that wouldn't be good either -- for example if someone wants to report a CoC violation against me, what should they do? I wish GH had a capability of filing private issues for this, but I think they don't.
Anyone who has suggestions for this, please speak up.

**Comment by winterdaemon** [comment]
@williamh, if [a _simpler_ and _less divisive_ CoC](https://github.com/systemd/systemd/blob/main/docs/CODE_OF_CONDUCT.md) is good enough for systemd, wouldn't that be worth considering?

**Comment by williamh** [comment]
@winterdaemon  I read the systemd CoC and the contributor covenant CoC, and I don't see what's divisive about the Contributor Covenant. The way I see it, it flushes things out and gives better examples.

**Comment by winterdaemon** [comment]
People seem pretty divided about it to me.

**Comment by Karasuma-Chitose** [comment]
Identity politics is inherently divisive.

**Comment by vapier** [comment]
> The only reason I haven't nerged this yet is I haven't quite decided what to do about the reporting address.

we can create a "moderators" team in the GH openrc org and tell people to contact that. then we add ourselves to it. we'll have to have said membership public of course.

> for example if someone wants to report a CoC violation against me, what should they do?

I don't think the contact method makes a difference here.  any small group like openrc will have this problem.  realistically there aren't that many people who care or have time to dedicate.  nature of the game.

> People seem pretty divided about it to me.

right, because if systemd is known for only one thing, it's how non-controversial it is.</sarcasm>

I'll note that the systemd issue you linked above was not without controversy either.  it was preemptively locked to avoid getting buried with garbage.  plenty of people want to bury their head and maintain the status quo.

if you have any specific issues to highlight, feel free, but "it's controversial" doesn't really cut it.  simpler is usually better, but I'm leaning more towards "widely adopted and understood", not "bespoke and unique".  I'll also note that the systemd PR you linked says parts of it were copied from contributor covenant.

@fufik made some salient points for example.

**Comment by williamh** [comment]
@vapier I like the idea of a moderators team. How would someone contact it privately?

**Comment by vapier** [comment]
I think it effectively turns into emailing us directly. but it offers a bit more flexibility with adding and removing people without updating the doc.

**Comment by vapier** [comment]
@williamh i noticed that GH has integrated reporting of abuse now.  i can change the e-mail to link to that documentation.  it would mean only things posted to GH could be reported, but i'm not sure we have any other community touchpoints ?
https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

**Comment by vapier** [comment]
@williamh i updated the contact info to point people to built in "Report Content" functionality that exists now in GH issues/discussions/etc...

i created a new "moderators" team as a fallback -- feel free to add yourself (i can't seem to add you directly).  i prefer that (and the description/framing) over the coc group as the point isn't "enforcement", it's about managing the community.  it's a much less adversarial pov imo.

**Comment by williamh** [comment]
@vapier  I checked out the integrated reporting. This looks like it will work for me, so I don't think we need the extra moderators team to handle it. Also, there appears to be a newer version of the contributer covenant, so I will diff our current CoC with it and push the updates to this pr if I have permission to do it.

**Comment by williamh** [comment]
@vapier It looks like there isn't a new version. I did find some formatting changes I want to sync with upstream, and I want to drop the moderator team. I will push that stuff as a separate commit toyour branch.
If it looks ok to you, let me know and I'll squash and merge.

**Comment by vapier** [comment]
we can always revise/re-add things if something is missing, so i'm fine with rolling things as-is

**Pull request merged**
