### PR TITLE
sh/init.sh.Linux.in: skip /proc sanity test if md5sum is missing

### PR DESCRIPTION
**Pull request by floppym**
Bug: https://bugs.gentoo.org/594534#c7

### CODE REVIEW

**Comment by dwfreed** [comment]
meh

**Comment by williamh** [comment]
If I have my choice, I would rather get rid of the /proc sanity test and just try to mount /proc if it isn't mounted.

**Comment by robbat2** [comment]
As the person that wrote this code, and cares about the case, please merge floppym's PR, and don't drop the /proc check.

**Comment by williamh** [comment]
Here's where I am on this p/r. We can keep the /proc check, but I question the value of the separate check for md5sum. The only time md5sum is not accessible is if /usr is separate and not mounted.

**Comment by floppym** [comment]
This is a simple patch to keep OpenRC working without /usr mounted. If you want to actively break that by refusing patches, that's up to you.

Merge this or close it.

**Comment by dwfreed** [comment]
Merged my PR.  Thanks again for your patch.

**Pull request closed without merging**
