### PR TITLE
.cirrus.yml: update runner to FreeBSD-11.3

### PR DESCRIPTION
**Pull request by gyakovlev**
simple update on 11 branch image.

### CODE REVIEW

**Comment by vapier** [comment]
the CI failed on the new 11-3 image.  want to take a look ?

**Comment by gyakovlev** [comment]
@vapier looks like CI is the problem itself, agent is not responding. Already tried to re-launch it yesterday, trying again.

**Comment by williamh** [comment]
It looks like this failed, can you check it?

Thanks.

**Comment by gyakovlev** [comment]
it keeps timing out without even starting, not sure anything can be done except getting lucky with free quota.

**Comment by vapier** [comment]
if their CI can't handle any real load, then trying to run against but always failing is going to just add noise and confusion to all our PRs right?

**Comment by gyakovlev** [comment]
what's strange is that 11.2 and 12.0 check works fine, something with scheduling 11.3 image on their gcloud.

I'll close this for now and revisit later, checking 11.2 is still ok, and it did not create any confusion before.

**Comment by vapier** [comment]
thanks. happy to upgrade if we can rely on it :).

**Pull request closed without merging**
